CUATRG/ViewModels/LibraryViewModel.cs
using CUATRG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CUATRG.ViewModels
{
    public class LibraryViewModel
    {
        public List<tblImage> Images { get; set; }
        public List<tblAlbum> Albums { get; set; }
        public List<tblEnvironmentalCondition> Conditions { get; set; }
        public List<tblColorMode> ColorModes { get; set; }
        public List<tblFeature> Features { get; set; }
        public List<tblFilter> Filters { get; set; }
        public decimal PageCount { get; set; }
        public decimal CurrentPage { get; set; }
    }
}

CUATRG/Controllers/LibraryController.cs
using CUATRG.Models;
using CUATRG.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CUATRG.Controllers
{
    public class LibraryController : Controller
    {
        private CUATRGEntities4 imageDB = new CUATRGEntities4();
        //
        // GET: /Search/
        [HttpGet]
        public ActionResult Index()
        {
            var viewModel = new LibraryViewModel()
            {
                Albums = imageDB.tblAlbums.ToList(),
                ColorModes = imageDB.tblColorModes.ToList(),
                Conditions = imageDB.tblEnvironmentalConditions.ToList(),
                Features = imageDB.tblFeatures.ToList(),
                Filters = imageDB.tblFilters.ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Search(string ddlAlbums, string ddlConditions, string ddlFeatures, string ddlFilters,
                                        string pageIndex) 
        {
            int recordsPerPage = 10;  
            IQueryable<tblImage> results = imageDB.tblImages.OrderBy(i => i.tblAlbum.ALB_Name);
            
            int albumId = -1;
             
            if (int.TryParse(ddlAlbums, out albumId))
            {
                results = results.Where(i => i.ALB_IDFkey == albumId);
            }

            int conditionid = -1;
            if (int.TryParse(ddlConditions, out conditionid))
            {
                results = results.Where(i => i.ENC_IDFkey == conditionid);
            }

            int featureId = -1;
            if (int.TryParse(ddlFeatures, out featureId))
            {
                results = results.Where(i => i.FTR_IDFkey == featureId);
            }

            int filterId = -1;
            if (int.TryParse(ddlFeatures, out filterId))
            {
                results = results.Where(i => i.FTR_IDFkey == featureId);
            }

            int recordCount = results.Count();

            //Pagination
            int page = -1;
            if (int.TryParse(pageIndex, out page))
            {
                results = results.Skip((page - 1) * recordsPerPage).Take(recordsPerPage);
            }
            else
            {
                page = 1;
                results = results.Take(recordsPerPage);
            } 
            
            List<tblImage> images = results.ToList();
            

            var data = new 
            {
                Images = images.Select( i => new {
                    Name = i.IMG_Name,
                    Path = ConfigurationManager.AppSettings["domain"] + i.IMG_Path + "//" + i.IMG_Name,
                    Album = i.tblAlbum.ALB_Name,
                    Condition = i.tblEnvironmentalCondition.ENC_Name,
                    Feature = i.tblFeature.FTR_Name,
                    AlbumId = i.tblAlbum.ALB_IDPkey,
                    ImageId = i.IMG_IDPkey
                }).ToList(),
                PageCount =(recordCount + recordsPerPage - 1) / recordsPerPage,
                CurrentPage = page
            }; 
            return Json(data);
        }

    }
}

CUATRG/Views/Library/Index.cshtml
@model CUATRG.ViewModels.LibraryViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container well">
    @*@using (Html.BeginForm("Index", "Library", FormMethod.Post, new { id = "calcForm" }))
        {*@
    <ol class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active"><a href="#">Library</a></li>

    </ol>
    <div class="container">

        <h1>Image Search</h1>
        <br />
        <div class="col-md-6">
            <div class="col-md-4">
                <div class="h4 margin-left">Album</div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    @Html.DropDownList("ddlAlbums",
                                            new SelectList(
                                                Model.Albums.Select(x => new { Value = x.ALB_IDPkey, Text = x.ALB_Name }),
                                                "Value",
                                                "Text"
                                               ),
                                             "-- Select Album --",
                                            new { @class = "form-control" })
                </div>

            </div>
            <div class="col-md-4">
                <div class="h4 margin-left">Env Cond</div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    @Html.DropDownList("ddlConditions",
                                              new SelectList(
                                                  Model.Conditions.Select(x => new { Value = x.ENC_IDPkey, Text = x.ENC_Name }),
                                                  "Value",
                                                  "Text"
                                                 ),
                                               "-- Select Condition --",
                                              new { @class = "form-control" })
                </div>

            </div>

        </div>
        <div class="col-md-6">
            <div class="col-md-4">
                <div class="h4 margin-left">Feature</div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    @Html.DropDownList("ddlFeatures",
                                            new SelectList(
                                                Model.Features.Select(x => new { Value = x.FTR_IDPkey, Text = x.FTR_Name }),
                                                "Value",
                                                "Text"
                                            ),
                                             "-- Select Feature --",
                                            new { @class = "form-control" })
                </div>

            </div>
            <div class="col-md-4">
                <div class="h4 margin-left"></div>
            </div>
            <div class="col-md-6">

                <div class="form-group">

                </div>

            </div>

        </div>



    </div>

    <br />


    <div class="col-md-6 col-sm-offset-2">
        <div class="col-md-3">
            <button type="button" class="btn btn-lg btn-primary btn-block" name="submit" onclick="Search(1)">Search</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-lg btn-default btn-block">Clear</button>
        </div>
    </div>
    <br />
    <br />
    <br />
    
    <table class="table table-striped" id="results">
        <thead id="resultsheader">
           
        </thead>
        <tbody id="resultsbody">
            
        </tbody>
    </table>
    
       
        @*}*@
        @Html.Hidden("CurrentPage", Model.CurrentPage)
</div>
<script>



    //$(document).ready(function () {

        function GetSearchUrl(pageId) {

            var cond = $("#ddlConditions").val()
            var feature = $("#ddlFeatures").val()
            var album = $("#ddlAlbums").val()
            var page = $("#CurrentPage").val()

            var url = "/Library/Search?pageIndex=" + pageId;

            if (album > 0) {
                url = url + "&ddlAlbums=" + album;
            }

            if (cond > 0) {
                url = url + "&ddlConditions=" + cond;
            }

            if (feature > 0) {
                url = url + "&ddlFeatures=" + feature;
            }
            return url;
        }

        function Search(pageId) {
            var url = GetSearchUrl(pageId);

            $.ajax({
                type: "POST",
                url: url,
                data: {},
                success: Success
            });
        }

        function Success(data) {
            
            $('#resultsbody').empty();
            $('#resultsheader').empty();

            var header = ''; 
            var rows = '';

            if (data.Images.length <= 0) {
                header = header.concat('<tr>')
                header = header.concat('<th colspan="5">No images found</th>')
                header = header.concat('</tr> ')
                $('#resultsheader').append(header)
                return;
            }

            
            header = header.concat('<tr>')
            header = header.concat('<th>Image</th>')
            header = header.concat('<th>Album</th>')
            header = header.concat('<th>Condition</th>')
            header = header.concat('<th>Feature</th>')
            header = header.concat('<th>View</th>')
            header = header.concat('</tr> ')

            for (var i = 0; i <= (data.Images.length - 1); i++)
            {
                rows = rows.concat('<tr class="align-middle">')
                rows = rows.concat('<td><img style="height:64px;width:64px" src="' + data.Images[i].Path + '" alt="Image" /></td>')
                rows = rows.concat('<td class="valign-center">' + data.Images[i].Album + '</td>')
                rows = rows.concat('<td class="valign-center">' + data.Images[i].Condition + '</td>')
                rows = rows.concat('<td class="valign-center">' + data.Images[i].Feature + '</td>')
                rows = rows.concat('<td class="valign-center">')
                rows = rows.concat('<a title="View Image" class="my_act_btn" target="_blank" href="/Album/Details?albumId=' + data.Images[i].AlbumId + '&imageId=' + data.Images[i].ImageId + '">') //Url.Action("Details", "Album", new { albumId = image[i].albumid, imageId = image[i].imageid })
                rows = rows.concat('<button type="button" class="btn btn-primary btn-xs">')
                rows = rows.concat('<span class="glyphicon "></span> View')
                rows = rows.concat('</button>')
                rows = rows.concat('</a>')
                rows = rows.concat('</td>')
                rows = rows.concat('</tr>')
            }

            rows = rows.concat('<tr>')
            rows = rows.concat('<td colspan="6">')
            rows = rows.concat('<ul class="pagination">') 

            for (var i = 1; i <= (data.PageCount); i++)
            {
                if (i == data.CurrentPage)
                {
                    rows = rows.concat('<li class="active"><a href="#" onclick="Search(' + i + ')">'+i+'</a></li>')
                }
                else
                {
                    rows = rows.concat('<li><a href="#" onclick="Search(' + i + ')">' + i +'</a></li>')
                }
            }
            rows = rows.concat('</ul>')
            rows = rows.concat('</td>')
            rows = rows.concat('</tr>')
 
            $('#resultsbody').append(rows)
            $('#resultsheader').append(header)
        }
    //});

</script>

CUATRG/Views/Library/Search.cshtml
@model CUATRG.ViewModels.LibraryViewModel

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 @if (Model.Images != null && Model.Images.Count > 0)
            {
                <table class="grid">
                    <tr>
                        <th>Name</th>
                        <th>Album</th>
                        <th>Color Mode</th>
                        <th>Condition</th>
                        <th>Feature</th>
                        <th>Filter</th>
                    </tr>

                    @foreach (CUATRG.Models.tblImage image in Model.Images)
                    {
                        <tr>
                            <td>@image.IMG_Name</td>
                            <td>@image.tblAlbum.ALB_Name</td>
                            <td></td>
                            <td>@image.tblEnvironmentalCondition.ENC_Name</td>
                            <td>@image.tblFeature.FTR_Name</td>
                            <td></td>
                        </tr>
                    }
                    

                </table>
            }